addons/orchestrator/orchestrator_node_factory.gd
=> Load resource scripts safely to avoid runtime errors

addons/orchestrator/orchestrator_node_factory.gd, addons/orchestrator/plugin.gd
=> Fix plug-in load order, removing const preloads

addons/orchestrator/views/main_view.gd
=> Save orchestrations on EditorPlugin apply_changes callback

addons/orchestrator/components/nodes/terminal/end_node.gd
=> Allow multiple end nodes

addons/orchestrator/components/nodes/flow_control/chance_node.gd, addons/orchestrator/components/nodes/flow_control/condition_node.gd, addons/orchestrator/components/nodes/flow_control/random_node.gd, addons/orchestrator/components/nodes/flow_control/repeat_node.gd, addons/orchestrator/components/nodes/logic/script_node.gd, addons/orchestrator/orchestrator.gd
=> Fix running orchestrations in editor

addons/orchestrator/views/main_view.gd
=> Update open file references when moving files

addons/orchestrator/components/nodes/logic/wait_for_action_node.gd
Added a logic node for waiting until an InputEventAction is pressed.
=> added wait for action node

addons/orchestrator/components/nodes/logic/show_message_node.gd
=> Fix speaker name behavior in runtime and editor UI

addons/orchestrator/components/editor/orchestration_graph.gd
=> GH-26 Fix when removing unconnected show message choices

addons/orchestrator/components/editor/plugin_download_update_dialog.gd, addons/orchestrator/components/editor/plugin_download_update_dialog.tscn, addons/orchestrator/components/editor/plugin_update_available_button.gd, addons/orchestrator/components/editor/plugin_update_available_button.tscn, addons/orchestrator/plugin.cfg, addons/orchestrator/plugin.gd, addons/orchestrator/views/main_view.gd, addons/orchestrator/views/main_view.tscn
=> GH-31 Add auto-update feature

addons/orchestrator/components/editor/node_tree.gd, addons/orchestrator/components/editor/node_tree_list.gd, addons/orchestrator/components/nodes/flow_control/chance_node.gd, addons/orchestrator/components/nodes/flow_control/condition_node.gd, addons/orchestrator/components/nodes/flow_control/random_node.gd, addons/orchestrator/components/nodes/flow_control/repeat_node.gd, addons/orchestrator/components/nodes/logic/expression_node.gd, addons/orchestrator/components/nodes/logic/script_node.gd, addons/orchestrator/components/nodes/logic/show_message_node.gd, addons/orchestrator/components/nodes/logic/wait_for_action_node.gd, addons/orchestrator/components/nodes/logic/wait_node.gd, addons/orchestrator/components/nodes/terminal/end_node.gd, addons/orchestrator/components/nodes/terminal/start_node.gd, addons/orchestrator/components/nodes/utility/comment_node.gd, addons/orchestrator/core/orchestration_node.gd
=> GH-33 Add node icons to node list and drag visual

addons/orchestrator/components/editor/orchestration_graph.gd, addons/orchestrator/components/editor/orchestration_graph_node.gd, project.godot
Resolves #22 
This work is currently based on Godot 4.2.dev5.  Once 4.2 has entered feature freeze, we'll look to merge this into the `main` branch and prepare for making 4.2 compatible builds.
=> GH-22 Initial support for Godot 4.2

src/editor/main_view.cpp
=> GH-48 Fix rendering of "Update Available" on dev builds

src/editor/graph/graph_edit.cpp, src/editor/graph/graph_edit.h, src/editor/graph/graph_node.cpp, src/editor/graph/graph_node.h
=> GH-54 Add cut/copy/paste/duplicate support

src/editor/graph/graph_edit.cpp, src/editor/graph/graph_edit.h
=> GH-56 Display status text on empty graphs

src/plugin/settings.cpp, src/script/instances/script_instance.cpp
=> GH-68 Fix `max_call_stack` property key

src/editor/main_view.cpp, src/plugin/plugin.cpp, src/plugin/plugin.h
=> GH-67 Restore open orchestrations

src/script/nodes/variables/local_variable.cpp, src/script/nodes/variables/local_variable.h
=> GH-66 Add local variable name and description

src/editor/graph/graph_node_pin.h
=> GH-82 Fix crash when dragging from node pins

src/editor/script_view.cpp, src/editor/script_view.h
=> GH-89 Correctly resolve new variable names on insert

src/editor/graph/graph_edit.cpp, src/editor/graph/graph_edit.h
=> GH-92 Add short-cut keybindings for Variable drag-n-drop

src/editor/graph/actions/action_menu.cpp, src/editor/graph/actions/action_menu.h, src/plugin/settings.cpp, src/plugin/settings.h
=> GH-84 Support favorites in "All actions" menu

src/editor/main_view.cpp
=> GH-114 Apply editor display scale to toolbar

src/script/instances/script_instance_placeholder.cpp
=> GH-116 Correctly update exported default values on nodes

src/script/nodes/functions/call_function.cpp
=> GH-111 Correctly handle return type as Variant

src/editor/main_view.cpp
=> GH-126 Render file list like Script tab file list

src/script/instances/script_instance.cpp
=> GH-121 Dispatch only script user-defined functions

docs/modules/ROOT/pages/nodes.adoc, src/editor/graph/actions/default_action_registrar.cpp, src/editor/graph/pins/graph_node_pin_file.cpp, src/editor/graph/pins/graph_node_pin_file.h, src/script/node_pin.h, src/script/nodes/dialogue/dialogue_message.cpp, src/script/nodes/scene/instantiate_scene.cpp, src/script/nodes/scene/instantiate_scene.h, src/script/nodes/script_nodes.cpp, src/script/nodes/script_nodes.h
=> GH-122 Introduce `Instantiate Scene` node

src/script/instances/script_instance.cpp, src/script/instances/script_instance_placeholder.cpp
=> GH-143 Return null rather than 0-sized property info list

docs/modules/ROOT/pages/nodes.adoc, src/editor/graph/actions/action_db.cpp, src/editor/graph/actions/action_menu_filter.h, src/editor/graph/actions/default_action_registrar.cpp, src/editor/graph/graph_edit.cpp, src/script/language.cpp, src/script/language.h, src/script/nodes/script_nodes.cpp, src/script/nodes/script_nodes.h, src/script/nodes/utilities/autoload.cpp, src/script/nodes/utilities/autoload.h
=> GH-136 Add support for accessing Godot autoloads

src/common/logger.h
=> GH-145 Use arch_linux compatible time formatting

src/common/variant_utils.cpp, src/editor/graph/actions/default_action_registrar.cpp, src/plugin/settings.cpp, src/script/nodes/data/arrays.cpp, src/script/nodes/data/arrays.h, src/script/nodes/data/compose.cpp, src/script/resource/internal/format_loader_instance.cpp, src/script/resource/internal/format_loader_instance.h, src/script/resource/internal/format_saver_instance.cpp, src/script/resource/internal/format_saver_instance.h
=> GH-159 Support all Packed-Array types

src/editor/main_view.cpp, src/editor/main_view.h, src/editor/script_view.cpp, src/editor/script_view.h
=> GH-155 Allow toggling component panel visibility

src/script/nodes/math/operator_node.cpp
=> GH-158 Correctly escape modulus title text

src/editor/graph/actions/default_action_registrar.cpp, src/script/nodes/variables/local_variable.cpp
=> GH-164 Add Local Variable types Object & Any

.github/workflows/build.yml
=> GH-167 Use `ubuntu-20.04` for GLIBC 2.31

src/script/script.cpp
=> GH-152 Do not change node icons when script attached

src/editor/graph/nodes/graph_node_comment.cpp, src/editor/graph/nodes/graph_node_comment.h
=> GH-173 Align comment node styles

src/editor/graph/actions/action_menu.cpp, src/plugin/settings.cpp
=> GH-176 Position all actions menu based on `center_on_mouse`

src/script/nodes/scene/instantiate_scene.cpp
=> GH-190 Do not cache instantiated scene node

src/editor/graph/graph_node.cpp, src/editor/graph/graph_node.h, src/editor/graph/graph_node_pin.cpp, src/editor/graph/graph_node_pin.h, src/script/nodes/functions/call_function.cpp, src/script/nodes/functions/call_function.h
=> GH-180 Support variadic function arguments

src/editor/editor.cpp, src/editor/graph/factories/graph_node_pin_factory.cpp, src/editor/graph/pins/graph_node_pin_bitfield.cpp, src/editor/graph/pins/graph_node_pin_bitfield.h, src/editor/graph/pins/graph_node_pin_enum.cpp, src/editor/graph/pins/graph_node_pins.h, src/script/node_pin.h, src/script/nodes/functions/call_function.cpp
=> GH-187 Add BitField input/default value support

src/script/nodes/functions/call_builtin_function.cpp, src/script/nodes/functions/call_member_function.cpp
=> GH-194 Reduce title text in call function nodes

src/script/nodes/resources/preload.cpp, src/script/nodes/resources/preload.h, src/script/nodes/scene/instantiate_scene.cpp, src/script/nodes/scene/instantiate_scene.h
=> GH-177 Fix type propagation for Preload and Instantiate Scene

src/common/scene_utils.cpp, src/common/scene_utils.h, src/editor/editor.cpp, src/editor/script_connection.cpp, src/editor/script_connections.h, src/editor/script_view.cpp, src/editor/script_view.h
=> GH-183 Signal function connection indicator/dialog

src/editor/graph/graph_edit.cpp, src/plugin/settings.cpp
=> GH-193 Allow highlighting selected nodes/connections

src/editor/graph/actions/action_menu.cpp
=> GH-176 Move dialog center prior to popup

src/editor/about_dialog.cpp, src/editor/editor.cpp, src/editor/main_view.cpp, src/editor/main_view.h, src/editor/updater.cpp, src/editor/updater.h, src/plugin/plugin.cpp, src/plugin/plugin.h
=> GH-208 Add auto-update functionality

src/editor/script_view.cpp
=> GH-202 Fix disconnect error on `tab_changed` signal

src/script/nodes/functions/call_function.cpp
=> GH-215 Initially set function arguments to default values

src/editor/graph/graph_edit.cpp, src/editor/graph/graph_edit.h, src/editor/script_view.cpp
=> GH-204 Spawn override function at center of view

src/editor/graph/actions/default_action_registrar.cpp, src/script/nodes/functions/call_function.cpp
=> GH-227 Correctly encode Godot vararg built-in functions

src/editor/graph/graph_edit.cpp
=> GH-230 Reconstruct existing node on sync request

src/script/resource/internal/format_loader_instance.cpp, src/script/resource/internal/format_saver_instance.cpp
=> GH-232 Remove superfluous warnings saving callable/signal types

src/common/scene_utils.cpp, src/common/scene_utils.h, src/editor/script_view.cpp, src/editor/script_view.h
=> GH-217 Add signal connection indicator for user-defined functions

src/common/method_utils.cpp, src/common/method_utils.h, src/editor/graph/actions/default_action_registrar.cpp, src/editor/graph/graph_node_spawner.cpp, src/script/nodes/functions/call_builtin_function.cpp, src/script/nodes/functions/call_builtin_function.h, src/script/nodes/functions/call_function.cpp, src/script/nodes/functions/call_function.h
=> GH-240 Standardize Method return value check

src/editor/graph/pins/graph_node_pin_bitfield.cpp, src/editor/graph/pins/graph_node_pin_bitfield.h
=> GH-237 Render @GlobalScope and class-scope bitfields uniformly

cmake/extension_db.cpp.in, cmake/generate_godot_extension_db.py, src/api/extension_db.cpp, src/api/extension_db.h
=> GH-239 Provide `ExtensionDB::is_class_enum_bitfield` look-up

src/script/node.cpp, src/script/node.h
=> GH-268 Do not serialize OScriptNode flags

src/editor/graph/actions/action_menu.cpp, src/editor/graph/actions/action_menu_item.h, src/editor/graph/actions/default_action_registrar.cpp, src/script/nodes/utilities/autoload.cpp, src/script/nodes/utilities/autoload.h
=> GH-253 Include registered autoloads in all actions menu

src/script/nodes/properties/property.cpp, src/script/nodes/properties/property.h, src/script/nodes/properties/property_get.cpp, src/script/nodes/properties/property_get.h
=> GH-266 Correctly resolve property class actions

src/editor/graph/actions/default_action_registrar.cpp, src/plugin/settings.cpp, src/script/nodes/memory/memory.cpp, src/script/nodes/memory/memory.h, src/script/nodes/script_nodes.cpp, src/script/nodes/script_nodes.h
=> GH-265 Support Object `new()` and `free()` nodes

src/editor/graph/pins/graph_node_pin_bitfield.cpp, src/editor/graph/pins/graph_node_pin_bitfield.h
=> GH-238 Rework/Improve Bitfield pin value rendering

src/script/nodes/data/compose.cpp
=> GH-248 Construct `Callable` with correct target reference

src/plugin/settings.cpp, src/plugin/settings.h
=> GH-297 Preserve setting order when setting is modified

src/editor/graph/graph_node_spawner.cpp
=> GH-282 Explicitly filter `_get` and `_set` methods

cmake/extension_db.cpp.in, cmake/generate_godot_extension_db.py, src/api/extension_db.cpp
=> GH-289 Fix built-in methods using PROPERTY_USAGE_NIL_IS_VARIANT

src/script/nodes/utilities/print_string.cpp, src/script/script.cpp
=> GH-287 Always call "Init" event if its wired

src/common/method_utils.cpp, src/common/method_utils.h, src/script/function.cpp, src/script/function.h, src/script/nodes/functions/function_terminator.cpp
=> GH-306 Fix functions to return Any types

src/editor/main_view.cpp, src/editor/main_view.h, src/editor/script_view.cpp, src/editor/script_view.h
=> GH-310 Support file/folder removed and files moved signals

src/editor/main_view.cpp, src/editor/main_view.h, src/plugin/plugin.cpp, src/plugin/plugin.h
=> GH-304 Track recently accessed orchestrations

src/common/version.h
=> GH-313 Add Godot version compile-time constant

src/editor/graph/actions/default_action_registrar.cpp, src/script/nodes/data/dictionary.cpp, src/script/nodes/data/dictionary.h, src/script/nodes/script_nodes.cpp
=> GH-318 Add `Dictionary Set` node

src/script/nodes/flow_control/for_each.cpp, src/script/nodes/flow_control/for_each.h
=> GH-315 Have `For Each` set Element as `Any`

src/editor/graph/pins/graph_node_pin_enum.cpp
=> GH-323 Fix enum persistence as a default value

src/script/nodes/utilities/self.cpp, src/script/nodes/utilities/self.h, src/script/script.cpp
=> GH-330 Fix Self node broken icon

src/common/method_utils.cpp, src/common/method_utils.h, src/editor/graph/graph_edit.cpp, src/editor/graph/graph_node.cpp, src/editor/graph/graph_node_pin.cpp, src/script/node.cpp, src/script/node.h, src/script/nodes/constants/constants.cpp, src/script/nodes/constants/constants.h, src/script/nodes/functions/call_builtin_function.cpp, src/script/nodes/functions/call_builtin_function.h, src/script/nodes/functions/call_member_function.cpp, src/script/nodes/functions/call_member_function.h, src/script/nodes/functions/call_static_function.cpp, src/script/nodes/functions/call_static_function.h, src/script/nodes/functions/event.cpp, src/script/nodes/functions/event.h, src/script/nodes/memory/memory.cpp, src/script/nodes/memory/memory.h, src/script/nodes/utilities/engine_singleton.cpp, src/script/nodes/utilities/engine_singleton.h, src/script/nodes/utilities/self.cpp, src/script/nodes/utilities/self.h
=> GH-221 View doc jump to class/constant/method Godot doc

src/script/script.cpp, src/script/script.h
=> GH-242 Add impl for ScriptLanguageExtension::_preferred_file_name_casing

src/common/file_utils.cpp, src/common/file_utils.h, src/common/scene_utils.cpp, src/common/scene_utils.h, src/editor/editor.cpp, src/editor/script_view.cpp, src/editor/script_view.h, src/editor/search/search_dialog.cpp, src/editor/search/search_dialog.h, src/editor/search/variable_classification_dialog.cpp, src/editor/search/variable_classification_dialog.h, src/plugin/inspector_plugin_variable.cpp, src/plugin/inspector_plugin_variable.h, src/plugin/plugin.cpp, src/plugin/plugin.h, src/script/nodes/data/type_cast.cpp, src/script/nodes/variables/variable_get.cpp, src/script/nodes/variables/variable_set.cpp, src/script/script.cpp, src/script/variable.cpp, src/script/variable.h
=> GH-301 Support class/enum/bitfield based variables

src/editor/editor.cpp, src/editor/getting_started.cpp, src/editor/getting_started.h, src/editor/main_view.cpp, src/editor/main_view.h
=> GH-345 Add landing page to main view

src/editor/search/search_dialog.cpp, src/editor/search/search_dialog.h, src/editor/search/variable_classification_dialog.cpp, src/editor/search/variable_classification_dialog.h
=> GH-339 Retain/store variable type filter across popup/restarts

src/editor/graph/graph_edit.cpp, src/editor/graph/graph_edit.h
=> GH-347 Improve base type indicator on graph toolbar

src/script/nodes/flow_control/for.cpp, src/script/nodes/flow_control/for_each.cpp
=> GH-350 Add for-each/for-loop abort output pin

src/editor/graph/graph_edit.cpp, src/editor/graph/graph_edit.h
=> GH-356 Fix knot rendering on Godot 4.2

src/script/nodes/scene/instantiate_scene.cpp
=> GH-385 Fix instantiate scene to respect input pin

src/editor/search/variable_classification_dialog.cpp
=> GH-382 Avoid recent history duplicates

src/editor/component_panels/component_panel.cpp
=> GH-390 Fix compatibility with the custom Godot minimal theme

src/editor/component_panels/component_panel.cpp, src/editor/component_panels/component_panel.h, src/editor/component_panels/functions_panel.cpp, src/editor/component_panels/functions_panel.h
=> GH-379 Component panels honor editor theme

src/common/settings.cpp, src/editor/graph/graph_edit.cpp
=> GH-365 Add disconnect control flow on drag option

src/editor/component_panels/component_panel.cpp
=> GH-392 Allow reselect in component panel item lists

src/editor/graph/graph_edit.cpp, src/script/nodes/functions/event.h
=> GH-366 Permit deleting event nodes like any other node

src/editor/graph/autowire_selections.cpp, src/editor/graph/autowire_selections.h, src/editor/graph/graph_edit.cpp, src/editor/graph/graph_edit.h, src/editor/graph/graph_node_pin.cpp, src/editor/graph/graph_node_spawner.cpp, src/editor/register_editor_types.cpp, src/script/node.cpp, src/script/node.h, src/script/nodes/functions/call_function.cpp
=> GH-364 Improved autowire with selection dialog

src/editor/graph/graph_edit.cpp, src/editor/graph/graph_edit.h, src/script/nodes/functions/function_entry.cpp, src/script/nodes/functions/function_entry.h, src/script/nodes/functions/function_result.cpp
=> GH-399 Spawn function return node when function has return value

src/editor/graph/graph_node.cpp
=> GH-401 Update component panel when using context menu delete

src/editor/graph/actions/action_menu.cpp, src/editor/graph/actions/action_menu_item.h, src/editor/graph/actions/default_action_registrar.cpp, src/script/nodes/data/dictionary.cpp, src/script/nodes/flow_control/select.cpp, src/script/nodes/flow_control/select.h, src/script/nodes/functions/call_builtin_function.cpp, src/script/nodes/functions/call_function.cpp, src/script/nodes/functions/call_member_function.cpp, src/script/nodes/functions/call_script_function.cpp, src/script/nodes/functions/call_static_function.cpp, src/script/nodes/math/operator_node.cpp, src/script/nodes/math/operator_node.h
=> GH-403 Remove redundant/superfluous text from node/pin names

src/editor/component_panels/variables_panel.cpp
=> GH-405 Update variable tooltip text

src/editor/component_panels/component_panel.cpp
=> GH-408 Correctly handle component tree expand/collapse

src/editor/graph/actions/default_action_registrar.cpp
=> GH-414 Fix method exclusion logic to allow virtual methods

src/script/script.h
=> GH-418 Fix toolbar update when base type changes

src/script/nodes/flow_control/for_each.cpp
=> GH-425 Fix upgrade bug with "For with Break" nodes

src/editor/script_view.cpp
=> GH-434 Display validation results on success

src/editor/component_panels/component_panel.cpp
=> GH-429 Fix compatibility with godot-minimal-theme 1.5.0

src/script/nodes/flow_control/for.cpp, src/script/nodes/flow_control/for_each.cpp
=> GH-431 Upgrade of For w/Break nodes autowires aborted

src/script/instances/node_instance.cpp, src/script/instances/node_instance.h, src/script/vm/execution_context.h, src/script/vm/script_vm.cpp, src/script/vm/script_vm.h
=> GH-423 Avoid reuse of default value instances

src/script/nodes/memory/memory.cpp
=> GH-416 Support instantiation of script-based classes

src/editor/script_view.cpp, src/editor/script_view.h
=> GH-438 Do not show validation success dialog on play game/scene

src/script/nodes/functions/call_function.cpp, src/script/nodes/functions/call_function.h
=> GH-428 Fix function return types that are enum/flags

src/editor/graph/actions/action_menu.cpp, src/editor/graph/actions/action_menu.h
=> GH-455 Fix collapse/expand fault in all actions menu

src/editor/graph/graph_edit.cpp
=> GH-453 Fix create knot GraphNode index out of bounds error

src/editor/editor_panel.cpp, src/editor/editor_panel.h, src/editor/file_dialog.cpp, src/editor/file_dialog.h, src/editor/graph/pins/graph_node_pin_file.cpp, src/editor/register_editor_types.cpp
=> GH-457 Introduce custom `FileDialog` implementation

src/editor/component_panels/variables_panel.cpp, src/editor/component_panels/variables_panel.h
=> GH-460 Avoid variable panel exponential updates

src/editor/graph/graph_knot.cpp, src/editor/graph/graph_knot.h
=> GH-452 Render Knots snapped to the grid

src/editor/graph/graph_node.cpp
=> GH-465 Apply "Refresh Nodes" option to all selected nodes

src/script/variable.cpp
=> GH-475 Fix variable property info init for class types

src/script/vm/script_vm.cpp
=> GH-476 Fix error handling in virtual machine

cmake/generate_godot_extension_db.py, src/api/extension_db.cpp
=> GH-477 Fix ExtensionDB generator

cmake/generate_godot_extension_db.py, src/api/extension_db.cpp
=> [2.0] Fix ExtensionDB Generator

src/editor/graph/actions/default_action_registrar.cpp
=> GH-482 Exclude internal properties from action menu

src/editor/component_panels/variables_panel.cpp, src/script/variable.cpp
=> GH-484 Show enum, bitfield, class icons in variable panel

src/common/settings.cpp
=> GH-486 Add connection color mapping for PackedVector4Array

src/script/nodes/functions/call_function.cpp
=> GH-487 Changing function argument type resets default value

src/script/nodes/input/input_action.cpp, src/script/nodes/input/input_action.h
=> GH-488 Update InspectorDock when ProjectSettings change

src/editor/graph/autowire_selections.cpp
=> GH-470 Operator node - always autowire first eligible pin

src/editor/graph/actions/action_menu.cpp, src/editor/graph/actions/action_menu.h
=> GH-502 Fix action menu item alignment

src/editor/graph/graph_node.cpp, src/editor/graph/graph_node.h, src/editor/graph/graph_node_pin.cpp, src/editor/graph/graph_node_pin.h
=> GH-490 Make PopupMenu instances dynamic for Node/Pins

src/editor/graph/graph_node.cpp
=> GH-505 Make node context menu items multi-select aware

src/editor/graph/actions/default_action_registrar.cpp, src/script/nodes/memory/memory.cpp
=> GH-510 Pass class type initialization to New Object nodes

src/script/nodes/functions/call_function.cpp, src/script/nodes/functions/call_function.h
=> GH-511 Add label to Enum/Bitfield return function values

src/orchestration/orchestration.cpp
=> GH-517 Run orphan fix-up during Orchestration post-initialize

src/editor/graph/graph_node_pin.cpp, src/script/target_object.h
=> GH-512 Correctly resolve target object

src/editor/component_panels/component_panel.cpp, src/editor/component_panels/component_panel.h, src/editor/editor_cache.cpp, src/editor/editor_cache.h, src/editor/editor_viewport.h, src/editor/script_editor_viewport.cpp, src/editor/script_editor_viewport.h
=> GH-496 Track editor graph state in editor cache

src/editor/graph/nodes/graph_node_default.cpp, src/editor/graph/pins/graph_node_pin_color.cpp, src/editor/graph/pins/graph_node_pin_numeric.cpp, src/editor/graph/pins/graph_node_pin_string.cpp
=> GH-491 Improve graph node left/right column rendering

src/common/property_utils.cpp, src/common/property_utils.h, src/common/scene_utils.cpp, src/common/scene_utils.h, src/editor/graph/pins/graph_node_pin_node_path.cpp, src/editor/graph/pins/graph_node_pin_node_path.h, src/editor/property_selector.cpp, src/editor/property_selector.h, src/editor/register_editor_types.cpp, src/editor/scene_node_selector.cpp, src/editor/scene_node_selector.h, src/script/nodes/scene/scene_node.cpp, src/script/target_object.h
=> GH-498 Improve NodePath dialogs for nodes and properties

src/script/nodes/data/compose.cpp, src/script/nodes/data/compose.h, src/script/nodes/data/decompose.cpp, src/script/nodes/data/decompose.h, src/script/nodes/functions/call_member_function.cpp, src/script/nodes/properties/property.cpp, src/script/nodes/properties/property.h, src/script/nodes/scene/scene_node.cpp, src/script/nodes/scene/scene_node.h, src/script/nodes/scene/scene_tree.cpp, src/script/nodes/scene/scene_tree.h, src/script/nodes/signals/emit_member_signal.cpp, src/script/nodes/signals/emit_member_signal.h
=> GH-473 Improve view documentation jump for nodes

src/editor/graph/graph_edit.cpp, src/editor/graph/graph_node_spawner.cpp
=> GH-472 Show event actions when dragging from input pins

src/editor/property_selector.cpp, src/editor/property_selector.h
=> GH-521 Fix compatibility issue with Godot 4.2.1 and `containsn`

src/common/settings.cpp, src/editor/theme/theme_cache.cpp
=> GH-59 Add configurable corner/border radius

src/editor/graph/actions/action_db.cpp, src/editor/graph/actions/action_menu.cpp, src/editor/graph/actions/action_menu.h, src/editor/graph/actions/default_action_registrar.cpp, src/editor/graph/actions/default_action_registrar.h, src/script/nodes/constants/constants.cpp, src/script/nodes/flow_control/branch.h, src/script/nodes/flow_control/for.h, src/script/nodes/flow_control/for_each.h, src/script/nodes/flow_control/while.h, src/script/nodes/utilities/engine_singleton.cpp, src/script/nodes/utilities/engine_singleton.h
=> GH-527 Improve all action search/category classifications

src/editor/component_panels/component_panel.cpp, src/editor/component_panels/component_panel.h, src/editor/editor_viewport.cpp, src/editor/editor_viewport.h, src/editor/script_editor_viewport.cpp
=> GH-529 Improve add component item workflow

src/script/instances/instance_base.cpp, src/script/instances/instance_base.h, src/script/instances/script_instance.h, src/script/instances/script_instance_placeholder.cpp, src/script/instances/script_instance_placeholder.h, src/script/script.cpp
=> GH-539 Fix placeholder instance clean-up

src/script/nodes/functions/call_member_function.cpp
=> GH-533 Ignore default value widgets on target pins

src/editor/graph/graph_edit.cpp
=> GH-542 Fix tween animation for focusing graph nodes

src/script/nodes/scene/scene_node.cpp
=> GH-532 Align Get Scene Node class on path change

src/editor/graph/pins/graph_node_pin_node_path.cpp, src/script/nodes/utilities/self.cpp, src/script/nodes/utilities/self.h
=> GH-534 Correctly resolve self for NodePath popups

src/script/graph.cpp
=> GH-547 Duplicate node instances on paste

src/script/nodes/data/compose.cpp, src/script/nodes/data/compose.h, src/script/nodes/data/decompose.cpp, src/script/nodes/data/decompose.h
=> GH-549 Add additional keywords for ComposeFrom/Decompose nodes

src/editor/inspector/property_info_container_property.cpp, src/editor/inspector/property_info_container_property.h, src/editor/plugins/inspector_plugins.cpp, src/editor/plugins/inspector_plugins.h, src/editor/plugins/orchestrator_editor_plugin.cpp, src/editor/register_editor_types.cpp, src/editor/search/search_dialog.cpp, src/script/function.cpp, src/script/function.h, src/script/nodes/functions/event.h, src/script/nodes/functions/function_terminator.cpp, src/script/nodes/functions/function_terminator.h, src/script/nodes/signals/emit_member_signal.cpp, src/script/nodes/signals/emit_signal.cpp, src/script/signals.cpp, src/script/signals.h
=> GH-497 Function/Signals support all class/argument types

src/editor/search/search_dialog.cpp, src/editor/search/search_dialog.h, src/editor/select_type_dialog.cpp
=> GH-560 Add global script filename to search results

src/script/nodes/functions/function_result.cpp
=> GH-563 Relax validation on function result node

src/script/nodes/variables/local_variable.cpp
=> GH-567 Correctly validate local variable node connection

src/script/nodes/input/input_action.cpp
=> GH-579 Raise breakpoint when input action has no action name

src/editor/editor_panel.cpp
=> GH-575 Correctly focus script on editor breakpoints

src/script/nodes/data/arrays.cpp, src/script/nodes/data/compose.cpp, src/script/nodes/dialogue/dialogue_message.cpp, src/script/nodes/flow_control/delay.cpp, src/script/nodes/flow_control/while.cpp, src/script/nodes/functions/call_function.cpp, src/script/nodes/functions/call_static_function.cpp, src/script/nodes/input/input_action.cpp, src/script/nodes/math/operator_node.cpp, src/script/nodes/scene/instantiate_scene.cpp, src/script/nodes/scene/scene_node.cpp, src/script/nodes/scene/scene_tree.cpp, src/script/nodes/signals/await_signal.cpp, src/script/nodes/utilities/autoload.cpp, src/script/nodes/variables/variable_get.cpp, src/script/nodes/variables/variable_set.cpp, src/script/vm/execution_context.cpp, src/script/vm/execution_context.h, src/script/vm/script_vm.cpp
=> GH-578 Make debugger errors more clear

src/script/nodes/functions/call_script_function.h
=> GH-583 Always show execution pins on user-defined script functions

src/editor/graph/pins/graph_node_pin_input_action.cpp
=> GH-582 Auto-select first action when node first placed

src/editor/component_panels/component_panel.cpp, src/editor/component_panels/component_panel.h, src/editor/component_panels/functions_panel.cpp, src/editor/component_panels/graphs_panel.cpp, src/editor/component_panels/signals_panel.cpp, src/editor/component_panels/variables_panel.cpp, src/orchestration/orchestration.cpp, src/orchestration/orchestration.h
=> GH-574 Strengthen validation for adding/renaming component items

src/editor/graph/graph_edit.cpp, src/editor/graph/graph_edit.h
=> GH-584 Disable knot creation inside node rect

src/editor/editor_panel.cpp, src/editor/editor_panel.h
=> GH-590 Use our own instance of ScriptCreateDialog

src/common/settings.cpp, src/editor/graph/graph_edit.cpp, src/editor/graph/graph_edit.h
=> GH-592 Add optional delete node confirmation dialog

src/editor/graph/pins/graph_node_pin_numeric.cpp, src/editor/graph/pins/graph_node_pin_numeric.h
=> GH-605 Improve numeric default value widget validation

src/editor/register_editor_types.cpp
=> GH-614 Mark several classes as internal

src/common/method_utils.cpp
=> GH-612 Fix view documentation not rendering

src/script/nodes/functions/call_script_function.h
=> GH-622 Revert commit 8f15816b092c9a92b878db319a496430925f8816

src/common/variant_utils.cpp, src/common/variant_utils.h, src/script/instances/script_instance_placeholder.cpp, src/script/instances/script_instance_placeholder.h, src/script/script.cpp, src/script/script.h
=> GH-626 Fix handling of script placeholder properties

src/editor/component_panels/component_panel.cpp, src/editor/component_panels/component_panel.h, src/editor/component_panels/functions_panel.cpp, src/editor/component_panels/functions_panel.h, src/editor/component_panels/graphs_panel.cpp, src/editor/component_panels/graphs_panel.h
=> GH-628 Synchronize signal slot disconnect UI updates

src/editor/graph/graph_edit.cpp
=> GH-634 Protect against double callback dispatch in Godot 4.2.x

doc_classes/OScriptNodeVariableGet.xml, src/editor/graph/graph_edit.cpp, src/editor/graph/graph_edit.h, src/editor/graph/graph_node.cpp, src/editor/graph/graph_node.h, src/editor/graph/graph_node_spawner.cpp, src/editor/graph/graph_node_spawner.h, src/script/nodes/variables/variable_get.cpp, src/script/nodes/variables/variable_get.h
=> GH-630 Enhance `VariableGet` with validation mode

src/script/nodes/input/input_action.cpp
=> GH-638 Guard against reconnection on node duplication

src/editor/plugins/orchestrator_editor_plugin.cpp
=> GH-653 Resize main toolbar icon with display scale

src/editor/graph/graph_edit.cpp, src/editor/graph/graph_edit.h, src/script/graph.cpp
=> GH-647 Store/Cache/Sync knots correctly on pin disconnects

src/common/scene_utils.cpp, src/common/scene_utils.h, src/editor/build_output_panel.cpp, src/editor/build_output_panel.h, src/editor/editor_panel.cpp, src/editor/editor_panel.h, src/editor/editor_viewport.cpp, src/editor/editor_viewport.h, src/editor/plugins/orchestrator_editor_plugin.cpp, src/editor/plugins/orchestrator_editor_plugin.h, src/editor/register_editor_types.cpp
=> GH-651 Move build/validate output to a bottom panel

src/script/function.h, src/script/nodes/functions/function_result.cpp, src/script/nodes/functions/function_result.h, src/script/nodes/functions/function_terminator.cpp
=> GH-646 Function graph validation for return node links

src/script/node.h, src/script/nodes/flow_control/for.cpp, src/script/nodes/flow_control/for.h, src/script/nodes/flow_control/for_each.cpp, src/script/nodes/flow_control/for_each.h, src/script/nodes/flow_control/while.cpp, src/script/nodes/flow_control/while.h, src/script/nodes/functions/function_result.cpp
=> GH-662 Exclude loop-based pins from return value check

src/editor/graph/graph_edit.cpp
=> GH-664 Use screen space for calculating paste position

src/script/nodes/math/operator_node.cpp
=> GH-667 Relax operator node connection requirements

src/editor/graph/graph_edit.cpp, src/editor/graph/graph_node.h
=> GH-666 Correctly handle Toggle Breakpoint keybind

src/common/method_utils.cpp, src/common/method_utils.h, src/script/nodes/functions/call_function.cpp
=> GH-675 Relax validation on function arguments with default values

src/script/node_pin.cpp
=> GH-648 Permit any output to connect to boolean input

src/editor/editor_panel.cpp
=> GH-687 Check script type on debugger signals

src/script/script.cpp, src/script/variable.cpp
=> GH-682 Fix exporting `Node` based variable types

src/script/serialization/binary_loader_instance.cpp, src/script/serialization/binary_saver_instance.cpp, src/script/serialization/instance.cpp, src/script/serialization/instance.h, src/script/serialization/variant_parser.cpp
=> GH-689 Introduce `PackedVector4Array` serialization handlers

src/common/dictionary_utils.cpp, src/common/dictionary_utils.h, src/editor/graph/graph_edit.cpp, src/editor/graph/graph_edit.h
=> GH-640 Add dragging function creates callable

src/script/nodes/functions/call_function.cpp, src/script/nodes/functions/call_function.h, src/script/nodes/functions/call_member_function.cpp
=> GH-684 Fix call mode semantics

src/editor/editor_panel.cpp
=> GH-696 Avoid error when disabling recent files option

src/editor/graph/graph_edit.cpp
=> GH-697 Synchronize graph on theme changes

src/script/nodes/data/type_cast.cpp, src/script/script_server.cpp
=> GH-701 Fix type cast honoring global script classes

src/editor/editor_panel.cpp
=> GH-703 Update FileSystemDock on file save as

src/script/serialization/binary_loader_instance.cpp, src/script/serialization/binary_loader_instance.h, src/script/serialization/binary_saver_instance.cpp, src/script/serialization/binary_saver_instance.h, src/script/serialization/instance.cpp, src/script/serialization/instance.h, src/script/serialization/serialization.cpp, src/script/serialization/text_loader_instance.cpp, src/script/serialization/text_loader_instance.h, src/script/serialization/text_saver_instance.cpp, src/script/serialization/text_saver_instance.h
=> GH-680 Fix loading external resources

src/editor/graph/graph_node.cpp, src/editor/graph/graph_node.h
=> GH-707 Add GraphNode alignment options

src/script/nodes/variables/variable_get.cpp, src/script/nodes/variables/variable_set.cpp
=> GH-718 Add variable descriptions to get/set node tooltips

src/common/settings.cpp, src/editor/editor_panel.cpp, src/editor/editor_panel.h, src/editor/graph/graph_edit.cpp
=> GH-729 Graph grid settings & cache left/right panel layouts

src/script/nodes/utilities/engine_singleton.cpp
=> GH-715 Alphabetically sort singleton list in inspector

src/editor/graph/graph_edit.cpp, src/script/graph.cpp, src/script/graph.h
=> GH-722 Correctly copy node state using `ui_copy` action

src/editor/component_panels/variables_panel.cpp, src/editor/graph/actions/default_action_registrar.cpp, src/editor/graph/graph_edit.cpp, src/script/nodes/variables/variable_set.cpp, src/script/nodes/variables/variable_set.h, src/script/variable.cpp, src/script/variable.h
=> GH-727 Add constant variable support

src/editor/updater.cpp
=> GH-743 Fix update picker is_after logic

src/common/file_utils.cpp, src/common/file_utils.h, src/common/scene_utils.cpp, src/editor/about_dialog.cpp, src/editor/component_panels/component_panel.cpp, src/editor/component_panels/functions_panel.cpp, src/editor/component_panels/signals_panel.cpp, src/editor/component_panels/variables_panel.cpp, src/editor/editor_cache.cpp, src/editor/editor_panel.cpp, src/editor/editor_viewport.cpp, src/editor/file_dialog.cpp, src/editor/graph/graph_edit.cpp, src/editor/graph/graph_edit.h, src/editor/graph/pins/graph_node_pin_node_path.cpp, src/editor/plugins/inspector_plugins.cpp, src/editor/plugins/orchestrator_editor_plugin.cpp, src/editor/plugins/orchestrator_editor_plugin.h, src/editor/script_editor_viewport.cpp, src/editor/search/search_dialog.cpp, src/editor/window_wrapper.cpp
=> GH-655 Use `EditorInterface::get_singleton` where possible

src/editor/graph/graph_edit.cpp, src/editor/graph/graph_edit.h, src/editor/graph/graph_node.cpp, src/editor/graph/graph_node.h, src/editor/graph/nodes/graph_node_comment.cpp
=> GH-738 Fix `Select Group` to include Knots and Nodes

src/editor/graph/graph_edit.cpp, src/editor/graph/graph_edit.h, src/editor/graph/graph_node.cpp, src/editor/graph/nodes/graph_node_comment.cpp, src/editor/graph/nodes/graph_node_comment.h
=> GH-737 Allow knot node operations within comment nodes

src/editor/graph/graph_edit.cpp
=> GH-752 Restrict arrow-key movement to only selected elements

src/editor/graph/actions/action_menu.cpp
=> GH-712 Clamp `All Actions` dialog within screen rect.

src/script/nodes/variables/variable_get.cpp, src/script/nodes/variables/variable_get.h
=> GH-756 Fix validated variable getter state consistency

src/editor/graph/graph_node.cpp, src/script/nodes/utilities/comment.cpp, src/script/nodes/utilities/comment.h
=> GH-427 Support custom icons for comment nodes

CMakeLists.txt
=> GH-765 Disable debug symbols on Linux/Android builds

src/editor/graph/actions/default_action_registrar.cpp, src/script/script.cpp
=> GH-771 Make exported variables searchable in `All Actions`

src/script/nodes/flow_control/sequence.h, src/script/nodes/functions/function_result.cpp
=> GH-774 Relax return node validation for sequence nodes

src/editor/plugins/orchestrator_editor_plugin.cpp
=> GH-778 Fix crash on Windows 10

src/editor/build_output_panel.cpp
=> GH-786 Add tooltip for `Orchestration Build` button

src/editor/graph/graph_node.cpp, src/editor/graph/graph_node.h
=> GH-467 Automatically fit-to-size graph nodes

src/script/nodes/scene/instantiate_scene.cpp
=> GH-798 Remove unnecessary instantiate scene cache

src/script/nodes/properties/property.cpp
=> GH-800 Temporarily disable some property get/set validation rules

src/editor/graph/actions/default_action_registrar.cpp
Fixes #761 
Without the fix
With the fix
=> GH-761 Use new ClassDB methods to fetch property getter/setter

src/editor/component_panels/component_panel.cpp, src/editor/component_panels/component_panel.h, src/editor/component_panels/functions_panel.cpp, src/editor/component_panels/functions_panel.h, src/editor/component_panels/graphs_panel.cpp, src/editor/component_panels/graphs_panel.h, src/editor/component_panels/signals_panel.cpp, src/editor/component_panels/signals_panel.h, src/editor/component_panels/variables_panel.cpp, src/editor/component_panels/variables_panel.h
=> GH-803 Component panels react to context-menu shortcuts

src/editor/graph/graph_edit.cpp, src/editor/graph/graph_edit.h
=> GH-714 Support `ui_cut` action in `GraphEdit` controls

src/editor/script_editor_viewport.cpp
=> GH-865 Prevent collapse to function with more than one data output pin

src/editor/plugins/orchestrator_editor_plugin.cpp, src/editor/plugins/orchestrator_editor_plugin.h
=> GH-857 Align tab highlighting with Script tab behavior

src/editor/graph/graph_edit.cpp
=> GH-848 Guard sync on theme change for when node is ready

src/script/instances/script_instance.cpp
=> GH-870 Dispatch `_notification` to script's graph

src/script/instances/instance_base.cpp
=> GH-872 Use correct struct type in memset

src/editor/graph/actions/action_menu.cpp, src/editor/graph/actions/action_menu.h
=> GH-844 Allow up/down and page up/down to move selection

project/addons/orchestrator/editor/icons/Compose.svg, project/addons/orchestrator/editor/icons/Decompose.svg, src/common/scene_utils.cpp, src/common/scene_utils.h, src/script/nodes/data/compose.cpp, src/script/nodes/data/decompose.cpp
=> GH-862 Change icons for compose/decompose script nodes

src/editor/graph/pins/graph_node_pin_enum.cpp, src/editor/graph/pins/graph_node_pin_enum.h
=> GH-877 Render enum drop-downs for script-specific enums

src/editor/component_panels/component_panel.cpp, src/editor/component_panels/component_panel.h, src/editor/component_panels/functions_panel.cpp, src/editor/component_panels/graphs_panel.cpp, src/editor/component_panels/macros_panel.cpp, src/editor/component_panels/signals_panel.cpp, src/editor/component_panels/variables_panel.cpp
=> GH-883 Delay component panel update by one frame

src/script/nodes/functions/call_function.cpp
=> GH-895 Return target when variant function is chained

src/script/nodes/signals/emit_member_signal.cpp
=> GH-897 Fix validation lookup for signal name on target

src/editor/graph/actions/default_action_registrar.cpp, src/script/nodes/functions/call_static_function.cpp, src/script/nodes/functions/call_static_function.h, src/script/script_server.cpp, src/script/script_server.h
=> GH-881 Support calling static script functions

src/script/variable.cpp
=> GH-879 Fix exporting node/resource variable types

.github/workflows/build.yml
=> GH-899 Move to Ubuntu 22.04 runners

src/editor/editor_panel.cpp, src/script/script.cpp
=> GH-903 Restrict script base type to adhere to node's class hierarchy

src/common/settings.cpp, src/common/settings.h, src/editor/graph/actions/action_menu.cpp, src/editor/graph/actions/action_menu.h
=> GH-914 Add setting to close all actions on focus lost

src/editor/inspector/editor_property_class_name.cpp, src/editor/inspector/editor_property_class_name.h, src/editor/plugins/inspector_plugins.cpp, src/editor/plugins/inspector_plugins.h, src/editor/plugins/orchestrator_editor_plugin.cpp, src/editor/register_editor_types.cpp, src/editor/search/search_dialog.cpp, src/editor/search/search_dialog.h, src/editor/select_class_dialog.cpp, src/editor/select_class_dialog.h
=> GH-908 Allow type cast to abstract class types

src/editor/graph/graph_edit.cpp, src/editor/graph/graph_node.h, src/editor/graph/nodes/graph_node_default.cpp, src/editor/graph/nodes/graph_node_default.h
=> GH-910 Updates wire colors when settings changed

src/editor/graph/graph_edit.cpp, src/script/nodes/scene/scene_node.cpp
=> GH-901 Support get scene node with unique names

src/editor/graph/pins/graph_node_pin_enum.cpp, src/script/script_server.cpp, src/script/script_server.h
=> GH-890 Fix enum dropdown for global script classes

src/editor/component_panels/functions_panel.cpp, src/editor/component_panels/graphs_panel.cpp, src/editor/component_panels/graphs_panel.h, src/editor/inspector/property_info_container_property.cpp, src/editor/plugins/inspector_plugins.cpp, src/editor/plugins/inspector_plugins.h, src/script/function.cpp, src/script/function.h, src/script/nodes/functions/function_terminator.cpp, src/script/nodes/functions/function_terminator.h, src/script/signals.cpp, src/script/signals.h
=> GH-943 Add function/signal description inspector fields

src/script/vm/script_state.cpp
=> GH-947 Verify script instance on signal callback

src/script/nodes/data/arrays.cpp
=> GH-849 Support python negative indexing on array nodes

src/editor/component_panels/functions_panel.cpp, src/editor/component_panels/functions_panel.h, src/editor/component_panels/variables_panel.cpp, src/editor/component_panels/variables_panel.h, src/orchestration/orchestration.cpp, src/orchestration/orchestration.h
Fixes #956 and #911
I had a stab at this as it seemed reasonably easy to implement and gave me a chance to get acquainted with the code base. I have tried to follow the code style and idioms used in the code base, but I might have added stuff in places where it's maybe not supposed to go, so please let me know if any changes are required to get this merged.
=> GH-956 add functionality to duplicate functions and variables in graphs

src/script/script.cpp, src/script/script.h
=> GH-972 Add ScriptExtension `_get_doc_class_name` override

src/common/resource_utils.cpp, src/common/resource_utils.h, src/editor/editor_viewport.cpp, src/script/script.cpp, src/script/script.h, src/script/serialization/variant_parser.cpp
=> GH-974 Support reloading script from disk

src/script/serialization/binary_saver_instance.cpp, src/script/serialization/text_saver_instance.cpp
=> GH-983 Reset script edit status on save

src/editor/graph/graph_node.cpp, src/editor/graph/graph_node_pin.cpp, src/script/nodes/functions/call_function.cpp, src/script/nodes/functions/call_function.h, src/script/nodes/functions/call_script_function.cpp, src/script/nodes/functions/call_script_function.h
=> GH-991 OScriptNodeCallFunction extend OScriptEditablePinNode

src/orchestration/orchestration.cpp
=> GH-956 Avoid extra execution pins on duplication

project/addons/orchestrator/orchestrator.gdextension
=> GH-1016 Fix wasm32 no-threads extension

.github/workflows/linux_builds.yml, CMakeLists.txt, project/addons/orchestrator/orchestrator.gdextension
=> GH-1014 Introduce Linux arm64 builds

src/editor/component_panels/functions_panel.cpp, src/editor/component_panels/graphs_panel.cpp, src/editor/component_panels/macros_panel.cpp, src/editor/graph/nodes/graph_node_comment.cpp, src/editor/graph/pins/graph_node_pin_node_path.cpp, src/editor/inspector/property_info_container_property.cpp, src/editor/script_editor_viewport.cpp, src/script/node_pin.cpp
=> Apply more granular checks for GODOT_VERSION

src/script/instances/instance_base.cpp
=> GH-1022 Do not allocate an empty method list

src/script/vm/script_vm.cpp
=> GH-1031 Make sure variable values are unique per instance
