src/editor/about_dialog.cpp
src/editor/editor.cpp
src/editor/graph/actions/action_menu.cpp
src/editor/graph/graph_edit.cpp
src/editor/graph/graph_node.cpp
src/editor/graph/graph_node_pin.cpp
src/editor/main_view.cpp
src/editor/main_view.h
src/editor/script_view.cpp
src/editor/script_view.h
src/editor/window_wrapper.cpp
src/editor/window_wrapper.h
src/plugin/plugin.cpp
src/plugin/plugin.h

Fixes #61 - adding floating window mode to the Orchestrator tab, restoring the window's position upon editor restarts.

GH-61 Add floating window mode

---

src/editor/graph/actions/action_menu_filter.h
src/editor/graph/actions/default_action_registrar.cpp
src/editor/graph/graph_edit.cpp
src/editor/graph/graph_node_pin.cpp
src/editor/graph/graph_node_pin.h
src/script/node.h
src/script/node_pin.cpp
src/script/node_pin.h
src/script/nodes/scene/scene_node.cpp
src/script/nodes/scene/scene_node.h

Fixes #52 - adding the ability to detect attached script members and methods

GH-52 Work with scene node's script properties & methods

---

src/editor/window_wrapper.cpp

GH-79 Avoid using deprecated `move_to_foreground`

---

src/common/variant_utils.h
src/script/nodes/data/compose.cpp

GH-112 Correctly coerce `ComposeFrom` values

---

src/editor/graph/actions/action_menu_filter.h
src/editor/graph/actions/action_registrar.h
src/editor/graph/actions/default_action_registrar.cpp
src/editor/graph/graph_edit.cpp
src/editor/graph/graph_node_spawner.cpp
src/editor/graph/graph_node_spawner.h

GH-130 Improve filtering of All Actions dialog

---

src/editor/graph/graph_node.cpp
src/editor/graph/graph_node.h
src/editor/script_view.cpp

Fixes #132 
Godot 4.3.dev4 introduced some changes to how `GraphNode` objects are rendered.  These changes guarantee that all script nodes in Orchestrator are rendered the same way regardless of whether Godot 4.2 or 4.3 is used.

GH-132 Improved graph node rendering

---

src/editor/graph/pins/graph_node_pin_enum.cpp
src/editor/graph/pins/graph_node_pin_enum.h
src/editor/graph/pins/graph_node_pin_numeric.cpp
src/editor/graph/pins/graph_node_pin_numeric.h
src/editor/graph/pins/graph_node_pin_string.cpp
src/editor/graph/pins/graph_node_pin_string.h
src/editor/graph/pins/graph_node_pin_struct.cpp
src/editor/graph/pins/graph_node_pin_struct.h

GH-182 The `ENTER` key releases node input focus

---

src/editor/graph/graph_edit.cpp
src/editor/graph/pins/graph_node_pin_object.cpp
src/script/node_pin.h
src/script/nodes/functions/call_function.cpp

GH-179 Function Call `Target` pin no longer autowired

---

src/editor/graph/actions/default_action_registrar.cpp
src/script/node.h
src/script/nodes/constants/constants.cpp
src/script/nodes/constants/constants.h
src/script/nodes/utilities/engine_singleton.cpp
src/script/nodes/utilities/engine_singleton.h

Fixes #222 
@GhostNr1, so this addresses some of the constants to be searchable; however, it doesn't satisfy all.  For example, this allows global constants, math constants, and singleton names to be searchable.
The issue right now with the other types is that the list of items is quite vast and depend on some context, i.e. an object type or class type, and I think ideally we may want to think about creating a cache for these.  If you think the above are satisfactory for now, we can certainly go with this; however, if you want a more flushed solution, then we'll need to revisit the class/type based constants.

GH-222 Allow some constant/singleton names be searchable

---

src/script/nodes/utilities/print_string.cpp

GH-273 Force `PrintStringUI` to ignore mouse events

---

src/editor/graph/graph_edit.cpp

GH-205 Dim wires when using `highlight_selected_connections`

---

src/editor/graph/graph_edit.cpp
src/script/nodes/functions/call_function.cpp
src/script/nodes/functions/call_function.h

GH-283 Support method chaining

---

src/editor/graph/graph_edit.cpp

GH-327 Fix editor crash on invalid reference

---

src/editor/script_view.cpp
src/editor/script_view.h

GH-76 Add scroll to item signal

---

src/editor/graph/graph_edit.cpp
src/editor/graph/graph_edit.h

Fixes #333 
This PR introduces a new option in the `GraphEdit` toolbar to switch between Line and Dot based patterns.
In addition, a small cosmetic enhancement to add some shadow/fidelity to the toolbar:
The code is guarded so that the cosmetic enhancement can be used by Orchestrator 2.0 and the new feature by 2.1 when rolling the GDExtension base forward to Godot 4.3.

GH-333 Implement GridPattern support for Godot 4.3

---

src/common/scene_utils.cpp
src/common/scene_utils.h
src/editor/graph/graph_edit.cpp
src/editor/graph/graph_edit.h
src/editor/graph/graph_node.cpp
src/editor/graph/graph_node.h
src/editor/graph/graph_node_pin.cpp
src/editor/graph/graph_node_pin.h
src/editor/graph/nodes/graph_node_comment.cpp
src/editor/graph/nodes/graph_node_default.cpp
src/editor/graph/nodes/graph_node_default.h
src/plugin/plugin.cpp
src/plugin/plugin.h
src/plugin/settings.cpp
src/plugin/settings.h
src/plugin/theme_cache.cpp
src/plugin/theme_cache.h

Fixes #343 
* Improve the responsiveness of theme changes.
* Move node resizing to a togglable feature using off as the default, with an on/off by default setting in project settings.
* Make the node background, border color, and selected border colors configurable
* Configure whether the minimap is shown or hidden by default in the project settings.
* Use the same msdf editor font as the Visual Shader, improving the text fidelity at higher zoom levels.
* Apply the border color uniformly around the entire node, like the visual shader UI.
* Adjust the default border color to be charcoal grey rather than black.

GH-343 Improve node styles, fidelity, and usability

---

src/editor/graph/graph_edit.cpp
src/editor/graph/graph_edit.h
src/script/graph.cpp
src/script/graph.h
src/script/script.cpp
src/script/script.h

GH-371 Fix zoom factor connection knot rendering

---

src/common/settings.cpp
src/editor/component_panels/component_panel.cpp
src/editor/component_panels/component_panel.h
src/editor/component_panels/functions_panel.cpp
src/editor/component_panels/graphs_panel.cpp
src/editor/component_panels/signals_panel.cpp
src/editor/component_panels/variables_panel.cpp
src/editor/component_panels/variables_panel.h
src/script/nodes/functions/call_function.h
src/script/nodes/functions/call_static_function.h
src/script/nodes/functions/event.h

GH-410 Add friendly names for Graph/Function component panels

---

src/script/function.cpp
src/script/signals.cpp

GH-255 Apply property usage fixup to functions/signals

---

src/editor/editor_cache.cpp
src/editor/editor_cache.h
src/editor/editor_panel.cpp
src/editor/editor_panel.h
src/editor/editor_viewport.cpp
src/editor/editor_viewport.h
src/editor/graph/graph_node.cpp
src/editor/graph/graph_node.h
src/editor/plugins/orchestrator_editor_debugger_plugin.cpp
src/editor/plugins/orchestrator_editor_debugger_plugin.h
src/editor/plugins/orchestrator_editor_plugin.cpp
src/editor/plugins/orchestrator_editor_plugin.h
src/editor/register_editor_types.cpp
src/script/instances/node_instance.h
src/script/instances/script_instance.cpp
src/script/instances/script_instance.h
src/script/language.cpp
src/script/language.h
src/script/node.cpp
src/script/node.h
src/script/script.cpp
src/script/vm/execution_context.h
src/script/vm/script_state.cpp
src/script/vm/script_state.h
src/script/vm/script_vm.cpp
src/script/vm/script_vm.h

GH-285 Add EditorDebugger Integration

---

src/editor/component_panels/functions_panel.cpp
src/editor/component_panels/functions_panel.h
src/editor/component_panels/graphs_panel.cpp
src/editor/component_panels/graphs_panel.h
src/editor/editor_panel.cpp
src/editor/editor_panel.h
src/editor/editor_viewport.h
src/editor/script_editor_viewport.cpp
src/editor/script_editor_viewport.h
src/script/language.cpp
src/script/language.h

Fixes #492 
This change aims to improve the creation of signal slot function handlers by ensuring that argument types are resolved as appropriate class types rather than always treating them as explicit `Variant` or basic types. In addition, this fix includes a few enhancements.
In prior releases, the `Orchestration` must be opened in the Orchestrator tab before a signal slot function can be added to the script.  If this was not the case, the signal would get registered in the scene but no function would be created in the script to handle the signal when fired.  
The callback handler method has been relocated to the main editor panel widget, which is always active in the Editor.  This means that if you create a signal slot handler function and pick a node that has an Orchestration on it, …

GH-492 Correctly resolve signal argument types

---

src/common/settings.cpp
src/editor/graph/graph_edit.cpp

I am trying to restore auto-arrange. Do you remember why it was removed?
https://github.com/Vahera/godot-orchestrator/assets/32321/68c54a55-b2e0-4042-9144-f0d063e86d99
I noticed that auto-arrange undo and redo is bugged - Will fill a bug report.
Also frames are not interacting.
I might be able to get these changed patched upstream.

Add a boolean setting to show the 'arrange' button in the UI.

---

.gitignore

This is a small PR that adds macOS and iOS `.dylib`, Linux and Android `.so`, and Web `.wasm` ignores. This prevents build artifacts from non-Windows platforms from showing up in diffs.

Add Mac, Linux, and Web ignores to .gitignore file

---

src/common/method_utils.cpp
src/common/method_utils.h
src/common/scene_utils.cpp
src/editor/graph/actions/action_menu.cpp
src/editor/graph/actions/default_action_registrar.cpp
src/editor/graph/actions/default_action_registrar.h
src/editor/graph/graph_edit.cpp
src/editor/graph/graph_node.cpp
src/editor/graph/graph_node_pin.cpp
src/editor/graph/graph_node_spawner.h
src/editor/graph/pins/graph_node_pin_object.cpp
src/script/node_pin.cpp
src/script/nodes/functions/call_function.cpp
src/script/nodes/functions/call_member_function.cpp
src/script/nodes/functions/call_static_function.cpp
src/script/nodes/properties/property.cpp
src/script/nodes/properties/property.h
src/script/nodes/properties/property_get.cpp
src/script/nodes/properties/property_set.cpp
src/script/nodes/utilities/engine_singleton.cpp
src/script/script.cpp
src/script/script_server.cpp
src/script/script_server.h

GH-537 Fix resolution of script on object types

---

src/editor/graph/actions/default_action_registrar.cpp
src/editor/search/variable_classification_dialog.cpp
src/script/script_server.cpp
src/script/script_server.h

GH-338 Support variables as script global class types

---

src/editor/graph/graph_edit.cpp
src/editor/graph/graph_edit.h
src/script/function.cpp

GH-551 Avoid duplicating return nodes on rename

---

src/editor/inspector/property_type_button_property.cpp
src/editor/select_type_dialog.cpp
src/editor/select_type_dialog.h

GH-603 Permit selecting abstract types for variable definitions

---

src/editor/script_editor_viewport.cpp
src/script/function.cpp
src/script/function.h
src/script/nodes/functions/call_function.cpp
src/script/nodes/functions/call_function.h
src/script/nodes/functions/call_script_function.h

Fixes #593 
- Pins should retain type
- Multiple pins should not have the same name
- Optional return node
- Script function call nodes use argument namse

GH-593 Fix collapse to function bugs

---

src/editor/select_type_dialog.cpp

GH-596 Render `int`, `float`, and `bool` with user-friendly names

---

src/script/nodes/utilities/print_string.cpp
src/script/nodes/utilities/print_string.h

GH-617 Retain `PrintString` defaults across node refreshes

---

src/common/variant_utils.cpp
src/common/variant_utils.h
src/editor/inspector/property_type_button_property.cpp
src/script/node_pin.cpp
src/script/nodes/variables/variable.cpp
src/script/nodes/variables/variable.h
src/script/nodes/variables/variable_get.cpp
src/script/nodes/variables/variable_get.h
src/script/nodes/variables/variable_set.cpp
src/script/nodes/variables/variable_set.h
src/script/variable.cpp
src/script/variable.h

Fixes #607 
- Add confirmation dialog with warning
- Attempt to coerce most common types between one another
- Retain VariableSet manual default values if they can be converted
- Break any connections with Variable Get/Set if types are incompatible

GH-607 Improve changing variable types

---

src/editor/inspector/property_type_button_property.cpp
src/editor/search/search_dialog.cpp
src/editor/search/search_dialog.h
src/editor/select_type_dialog.cpp
src/editor/select_type_dialog.h

Fixes #595 
- All search items (excluding root item) are collapsed when the search box is empty.
- There is no initial search text in the search box.
- All global enums and bitfields have been relocated under new `Types/Global Enum` and `Types/Global Bitfield` categories.
- Fixes clearing search box to reset favorite button press state.

GH-595 Improve initial rendering of variable type selection

---

src/common/settings.cpp
src/script/nodes/functions/call_member_function.cpp
src/script/nodes/functions/call_member_function.h
src/script/nodes/functions/call_script_function.h

GH-632 Add new function call node color variants

---

src/script/node_pin.cpp

GH-642 Allow `Object` to connect to `Boolean` pins

---

src/script/node_pin.cpp

GH-643 Allow `String` to connect to `StringName` pins

---

src/script/vm/script_state.cpp
src/script/vm/script_state.h

GH-674 Fix Await signal to work with parameterized signals

---

src/script/nodes/utilities/print_string.cpp

GH-636 Don't wrap text in `PrintStringUI`

---

src/script/nodes/functions/call_function.h

GH-691 Use function argument names rather than class names

---

src/editor/plugins/orchestration_editor_export_plugin.cpp
src/script/nodes/functions/call_function.cpp

GH-693 Correctly resolve target object on method chaining

---

src/editor/about_dialog.cpp
src/editor/editor_panel.cpp
src/editor/graph/actions/action_menu.cpp
src/editor/graph/pins/graph_node_pin_color.cpp

GH-705 Correctly size controls based on editor scale

---

src/editor/graph/graph_knot.cpp
src/editor/graph/graph_knot.h

GH-736 Fix knot movement/alignment

---

src/common/variant_utils.cpp
src/common/variant_utils.h
src/script/instances/script_instance_placeholder.cpp

GH-794 Fix default value evaluation in ScriptPlaceHolderInstance

---

src/script/nodes/dialogue/dialogue_message.cpp
src/script/nodes/properties/property_get.cpp
src/script/nodes/properties/property_set.cpp
src/script/nodes/utilities/print_string.cpp

GH-796 Guard against `get_current_scene` returning null

---

src/script/instances/script_instance.cpp
src/script/vm/script_vm.cpp
src/script/vm/script_vm.h

GH-807 Support named lookup of signals, used by `await` keyword

---

src/common/method_utils.cpp
src/common/method_utils.h
src/editor/graph/graph_edit.cpp
src/editor/graph/graph_edit.h
src/script/nodes/signals/emit_signal.cpp
src/script/nodes/variables/variable_set.cpp
src/script/signals.cpp
src/script/signals.h
src/script/variable.cpp
src/script/variable.h

Fixes #724 
This change allows the copy-n-paste of nodes that call script functions, emit script signals, or get or set script variable values. The granular behavior for each node type is as follows:
* Emit Script Signal Node
* If the signal does not exist, it's created before the emit signal node is placed.
* If the signal exists with the name, but the definition differs, an error is displayed & paste fails.
* If the signal exists with the same name and the definition matches, the emit signal node is placed only.
* Get/Set Variable Node
* If the variable does not exist, it's created before the get/set variable node is placed.
* If the variable exists with the same name but is defined differently, an error is displayed & paste fails.
* If the variable exists with the same name and the …

GH-724 Fix copy-n-paste between two orchestrations

---

README.md

This corrects a couple of small grammar issues and formatting.

Correct small grammatical issues

---

src/editor/graph/graph_node_pin.cpp
src/editor/graph/graph_node_pin.h
src/orchestration/orchestration.cpp
src/orchestration/orchestration.h
src/script/variable.cpp
src/script/variable.h

GH-811 Correctly initialize promoted variables

---

src/common/settings.cpp
src/script/nodes/dialogue/dialogue_message.cpp

Adds a setting in Project Settings for the user to set the PackedScene that is instanced by default when a Dialogue Message Node runs in an Orchestrator Script.
Aims to fix issue #838.
**Note**: This is a re-creation of the Branch in PR #840. A rebase was executed incorrectly and the commit history got all messed up. This PR aims to accomplish the exact same goal with none of the clutter created by the aforementioned blunder.

Added default_scene to ProjectSettings (The Sequel)

---

README.md

Fixes #906 
Docs PR - https://github.com/CraterCrash/godot-orchestrator-docs/pull/100

GH-906 Update README Discord link

---

src/editor/graph/pins/graph_node_pin_factory.cpp
src/editor/graph/pins/graph_node_pin_string.cpp
src/editor/graph/pins/graph_node_pin_string.h
src/editor/register_editor_types.cpp
src/script/node.h
src/script/node_pin.cpp
src/script/node_pin.h
src/script/nodes/functions/call_member_function.cpp
src/script/nodes/functions/call_member_function.h
src/script/nodes/signals/await_signal.cpp
src/script/nodes/signals/await_signal.h

Fixes #535 
An `OScriptNode` can now override the `get_suggestions` function, which returns a `PackedStringArray` of suggestion options based on the supplied pin that will be shown in a `PopupMenu`. This is used only for `OrchestratorGraphNodePinString` pin types.

GH-535 Add string-based pin suggestion options

---

doc_classes/OScript.xml
src/common/varray.h
src/editor/graph/actions/default_action_registrar.cpp
src/script/language.cpp
src/script/nodes/functions/call_builtin_function.cpp
src/script/register_script_types.cpp
src/script/utility_functions.cpp
src/script/utility_functions.h
src/script/vm/script_vm.cpp

Fixes #821 
This change introduces the following built-in functions:
* len
* print_debug
* print_stack
* get_stack
* type_exists
While many of these are mostly useful for debugging, things like `type_exists` and `len` bring GDScript built-in functions to the Orchestrator plug-in.  The `len` function specifically supports all variant types, without needing to call the specific size or equivalent method on the variant type directly.

GH-821 Introduce Orchestration built-in functions

---

src/editor/editor_panel.cpp

GH-995 Clear inspector when closing an Orchestration

---

README.md

Fix unexpected behavior of icon orchestrator_menu_image_500px.png appearing as way too big with height=30 and changed it to height=20 to work as (supposedly) expected
Happened when tested in Chromium (Brave) and WebKit (Safari) browsers so unexpected behavior from GitHub markdown preview because the height became too big and overflowed the height of the line I suppose

Fix README icon behavior
